# nginx_server/Dockerfile

# Usamos la imagen oficial de Nginx
FROM nginx:alpine

# Copiamos nuestro archivo HTML al directorio donde Nginx busca los archivos estáticos

COPY index.html /usr/share/nginx/html/