# python_app/Dockerfile

FROM python:3.9-slim-buster

WORKDIR /app

COPY app.py .

# Mantiene el contenedor "vivo" esperando
CMD ["tail", "-f", "/dev/null"] 
# Podemos usar: CMD ["sleep", "infinity"] 
# O: CMD ["bash"] # Si necesitamos una shell en el contenedor para hacer cosas.